---
- name: Rolling Restart Vault Nodes
  hosts: "{{ target | default('vault_nodes') }}" 
  become: true  
  tasks:
    - name: Destroy All Vault
      shell: docker compose down
      args:
        chdir: "{{ vault_base_dir }}"